
CREATE TABLE AUTORES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    NACIONALIDADE VARCHAR2(255)
);

CREATE TABLE LIVROS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(255) NOT NULL,
    ANO_PUBLICACAO NUMBER(4,0),
    ID_AUTOR NUMBER,
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(ID)
);
